name: CI

on:
  push:
    branches:
      - main
      - development

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11.24.0
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [22, 24]
        include:
          - os: macos-latest
            node_version: 24
          - os: windows-latest
            node_version: 24
      fail-fast: false

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11.24.0
          run_install: false

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11.24.0
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Verify package
        run: pnpm verify-package

  examples:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        example: [cjs-full, ejs-full]
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11.24.0
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Install ${{ matrix.example }} example
        run: pnpm install --dir examples/${{ matrix.example }}

      - name: Run ${{ matrix.example }} example
        run: pnpm test:examples examples/${{ matrix.example }}
